//
//  TemplateOutputConsumer.swift
//  Notenik Lib
//
//  Created by Herb Bowie on 7/25/22.
//
//  Copyright © 2022 - 2023 Herb Bowie (https://hbowie.net)
//
//  This programming code is published as open source software under the
//  terms of the MIT License (https://opensource.org/licenses/MIT).
//

import Foundation

/// A protocol for a class that can do something useful with the output from a merge Template.
/// The implementation will vary by platform. 
public protocol TemplateOutputConsumer {
    
    /// Supply a source that can be used later to refresh a query.
    func supplySource(_ source: TemplateOutputSource)
    
    /// Do something useful with the output generated by a Template.
    func consumeTemplateOutput(_ templateOutput: String)
}
